# Generated by Django 3.2.7 on 2021-09-03 18:06

from django.db import migrations

def insertPostData(apps,schema_editor):
    Post = apps.get_model("post","post")

    for x in range(1,5):
        post = Post.objects.create(title=f"title {x}",description=f"Test Description {x}")
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertPostData)
    ]
