# Generated by Django 3.2.7 on 2021-09-06 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210906_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 23, 4, 50, 8726), verbose_name=datetime.datetime(2021, 9, 6, 23, 4, 50, 8726)),
        ),
    ]
